#ifndef SMBUS_PROTOCOLS_H
#define SMBUS_PROTOCOLS_H

/*****************************************************************************/
/* Enums                                                                     */
/*****************************************************************************/

/**
 * @enum    SMBUS_PROTOCOL_COMMANDS
 * @brief   List of the system-defined protocol command values
 */
typedef enum SMBUS_PROTOCOL_COMMANDS
{
    SMBUS_PROTOCOL_QUICK_COMMAND_LO = 1,
    SMBUS_PROTOCOL_QUICK_COMMAND_HI,
    SMBUS_PROTOCOL_SEND_BYTE,
    SMBUS_PROTOCOL_RECEIVE_BYTE,
    SMBUS_PROTOCOL_WRITE_BYTE,
    SMBUS_PROTOCOL_WRITE_WORD,
    SMBUS_PROTOCOL_READ_BYTE,
    SMBUS_PROTOCOL_READ_WORD,
    SMBUS_PROTOCOL_PROCESS_CALL,
    SMBUS_PROTOCOL_BLOCK_WRITE,
    SMBUS_PROTOCOL_BLOCK_READ,
    SMBUS_PROTOCOL_BLOCK_WRITE_BLOCK_READ_PROCESS_CALL,
    SMBUS_PROTOCOL_HOST_NOTIFY,
    SMBUS_PROTOCOL_WRITE_32,
    SMBUS_PROTOCOL_READ_32,
    SMBUS_PROTOCOL_WRITE_64,
    SMBUS_PROTOCOL_READ_64,
    SMBUS_ARP_PROTOCOL_PREPARE_TO_ARP,
    SMBUS_ARP_PROTOCOL_RESET_DEVICE,
    SMBUS_ARP_PROTOCOL_GET_UDID,
    SMBUS_ARP_PROTOCOL_ASSIGN_ADDRESS,
    SMBUS_ARP_PROTOCOL_GET_UDID_DIRECTED,
    SMBUS_ARP_PROTOCOL_RESET_DEVICE_DIRECTED,
    SMBUS_PROTOCOL_NONE

} SMBUS_PROTOCOL_COMMANDS;

#endif  /* SMBUS_PROTOCOLS_H */
